### ISSUE TITLE
 ValueError: I/O operation on closed file problem.

### ISSUE THREAD

**Issue by ohggbear** [snowby666/poe-api-wrapper#153]
There was a problem when uploading the file attachment through the API. I can read the file normally using the URL, but if I use a local file, I encounter a "ValueError: I/O operation on closed file" problem.

**Comment by sunnysktsang** [comment]
Hello @ohggbear,

It sounds like you are encountering an issue that was recently addressed in the repository. This issue typically occurs when file streams are not properly managed, leading to attempts to operate on a file that has been prematurely closed.

I recommend checking out the pull request where this issue was fixed. It might provide you with the solution you need. Here’s the link to the pull request for your reference:
[#149 [Fix issue with file handling in generate_file function](https://github.com/snowby666/poe-api-wrapper/pull/149)]

Please ensure that your local copy of the repository is updated with this fix. You can update your repository by pulling the latest changes:
`git checkout main`
`git pull origin main`

If the issue persists after ensuring the updates are incorporated, please double-check your file handling code to ensure it aligns with the best practices shown in the pull request. If there are still problems, feel free to share more details here, and I’d be happy to take another look.

Best regards,
Sunny

**Comment by snowby666** [comment]
Closing since the PR is merged
