### ISSUE TITLE
RuntimeError("Timed out waiting for response.")

### ISSUE THREAD

**Issue by huiye19** [snowby666/poe-api-wrapper#189]
I have tried for multiple times today, but it always shows the error below:

raise RuntimeError("Timed out waiting for response.")
RuntimeError: Timed out waiting for response.

On poe website, I can get responses. But it seems server cannot get it from the website. How to fix this issue?

**Comment by David-Zeng** [comment]
I'm experiencing the same issue

**Comment by jishux2** [comment]
I encountered a similar issue where even after receiving the response, the code still times out while waiting for new messages. Upon testing, I believe the issue lies in the line [`if not response["title"]`](https://github.com/snowby666/poe-api-wrapper/blob/3022b9c513c8c22a01871d6e89158483d08ea0f9/poe_api_wrapper/async_api.py#L931). This is because all the messages with a 'complete' `state` that I've received so far have a 'None' `title`. It might be necessary to modify the condition for checking.

**Comment by snowby666** [comment]
This is fixed since theres no chatTitleUpdate from websocket anymore
