### ISSUE TITLE
gpt-4（beaver）bot not the real one

### ISSUE THREAD

**Issue by wingeva1986** [snowby666/poe-api-wrapper#9]
Asking the gpt-4（beaver）bot is not the same as using on official website，it acts like chatgpt(3.5)

**Comment by snowby666** [comment]
Can you open the poe.com tab while using the API to check if its sending to gpt-4?

**Comment by wingeva1986** [comment]
I checked the website after using the api. got the result below:
![Screenshot_20230828_233959_com example hikerview](https://github.com/snowby666/poe-api-wrapper/assets/35324882/cd50ef61-1ff3-435e-95f7-f861d6b6ab50)
the answer was 3.5 style,which didn't see 鲁迅 and 周树人 is the same person.

And then I asked the same question on the website, got different right answer below:
![Screenshot_20230828_233941_mark via](https://github.com/snowby666/poe-api-wrapper/assets/35324882/1d9c043d-b675-4bb4-b45f-328ad0a76488)




I think it's the same problem like poe-api.
https://github.com/ading2210/poe-api/issues/205

**Comment by wingeva1986** [comment]
> I see. Maybe this bug is related to the OpenAI API on Poe server? I will do a research for this later

I think it's not a bug but the poe's trick to prevent abusing, because something similar happenned before,which forced all user-built gpt-4 bot downgrade  to gpt-3.5.

**Comment by zp96324511** [comment]
poe recognizes unofficial client call, forces drop back to version 3.5 response

**Comment by 24-Fahed** [comment]
![截图 2023-11-18 18-23-16](https://github.com/snowby666/poe-api-wrapper/assets/76234865/2016ae8e-f3e2-45c4-88be-cd6ffdf0d5c4)
![{3801C2BF-D586-DE40-B234-327227B5FB45}](https://github.com/snowby666/poe-api-wrapper/assets/76234865/d58a2bc6-4260-4a30-9c1c-46e9d7472030)
![截图 2023-11-18 18-37-22](https://github.com/snowby666/poe-api-wrapper/assets/76234865/f0e4d004-5bee-492f-a459-4f345a80fac5)

At first i use chinese ask poe's gpt4 qustion and he tell me he is GPT3.5(The last bit of dialog in the second picture is roughly in Chinese: "I simulated gpt4 based on gpt3"), then, i use english ask poe's gpt4 he tell me he is gpt4. I really hope poe is intentionally blocking me because it detects Chinese users, But poe god forbid fixed the “bug”(in picture 3) that it wasn't gpt4 and deleted the conversation between me and him, which makes me wonder if it is indeed a faked gpt4. But this could all be me, based on the fact that it will delete the dialog I must say that he really is an “excellent gpt4". Of cause poe is not using openai's interface(in https://poe.com/about), if it is poe's own training gpt4 but using earlier data to cause the answer to be wrong is also "understandable".

**Comment by snowby666** [comment]
Closing since this a problem with poe.com itself
